// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5NgOcIqweXIQ-CHv7sLeFpPFBBv3JiAM',
    appId: '1:131746749075:web:afa143db545f19dcf14b66',
    messagingSenderId: '131746749075',
    projectId: 'blooddonorapp-4745a',
    authDomain: 'blooddonorapp-4745a.firebaseapp.com',
    storageBucket: 'blooddonorapp-4745a.firebasestorage.app',
    measurementId: 'G-2NSMGEH8NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADALeIphzEaDcfUzDxhBwfVXxfv5Fa4GE',
    appId: '1:131746749075:android:79e7a160718a54c0f14b66',
    messagingSenderId: '131746749075',
    projectId: 'blooddonorapp-4745a',
    storageBucket: 'blooddonorapp-4745a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi5AxzP5a6EBi1ADDwP2vbJaXGPZBfuGI',
    appId: '1:131746749075:ios:49f17e61057bf8f1f14b66',
    messagingSenderId: '131746749075',
    projectId: 'blooddonorapp-4745a',
    storageBucket: 'blooddonorapp-4745a.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi5AxzP5a6EBi1ADDwP2vbJaXGPZBfuGI',
    appId: '1:131746749075:ios:49f17e61057bf8f1f14b66',
    messagingSenderId: '131746749075',
    projectId: 'blooddonorapp-4745a',
    storageBucket: 'blooddonorapp-4745a.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5NgOcIqweXIQ-CHv7sLeFpPFBBv3JiAM',
    appId: '1:131746749075:web:a0a76952add38360f14b66',
    messagingSenderId: '131746749075',
    projectId: 'blooddonorapp-4745a',
    authDomain: 'blooddonorapp-4745a.firebaseapp.com',
    storageBucket: 'blooddonorapp-4745a.firebasestorage.app',
    measurementId: 'G-X7Z9QQ8MZ9',
  );
}
